id: org.eclipse.che.vscode-redhat.java
version: 0.43.0
type: VS Code extension
name: Language Support for Java(TM)
title: Language Support for Java(TM) by Red Hat
description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
url: https://github.com/redhat-developer/vscode-java/releases/download/v0.43.0/redhat.java-0.43.0.vsix
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
publisher: Red Hat, Inc.
repository: https://github.com/redhat-developer/vscode-java
category: Language
firstPublicationDate: "2019-04-23"
attributes:
  containerImage: "eclipse/che-remote-plugin-runner-java8:next"